version: '3.8'

services:
  db:
    container_name: postgres-trello-api
    image: postgres:14.0-alpine
    restart: always
    environment:
      - POSTGRES_USER=${USERNAME}
      - POSTGRES_PASSWORD=${PASSWORD}
      - POSTGRES_DB=${DATABASE}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - ${PORT}:${PORT}
